### ISSUE TITLE
Question 3: doesn't fill na's

### ISSUE THREAD

**Issue by pjsharpe07** [Thinkful-Ed/data-201-assignment-solutions#1]

**Comment by leravalencia** [comment]
the same for me

**Comment by pjsharpe07** [comment]
Not many details here and I couldn't 100% confirm which section of the code I had issues.

However, I assume it was referencing some `.fillna` functionality which was fixed [with this commit](https://github.com/Thinkful-Ed/data-201-assignment-solutions/commit/120779b1a6a1ed484946ac344fc009e832227f7d?diff=split#diff-e40f5089b929b0703e10c6e7f0f8fa8b1e14cec829e72cda60c305b9bac7b3d7R229-R243)

Marking as closed - thanks @tiagofassoni for the fix here.
